skip git_changes if the source_type is set to API
If the source type is set to API the git_changes is set to empty list. Calling a webhook is throwing below error
File "/usr/local/lib/python3.10/site-packages/opal_server-0.5.0-py3.10.egg/opal_server/policy/webhook/api.py", line 75, in trigger_webhook
    urls = git_changes.urls
           └ []

AttributeError: 'list' object has no attribute 'urls'